### ISSUE TITLE
一些更加具体的要求

### ISSUE THREAD

**Issue by wangshouh** [Web3-Club/Chain-Farm#2]
## 土地属性

土地需要何种属性？

比如

- 具有普通属性、冰属性或者火属性，以及另一些适用于玩法的属性

- 我们必须使用 `seed` 代表土地种植了哪些种子？

- 土地这个属性对应的数据是什么？

| 属性 | 作用 | 备注 |
| ---- | ----- | ----- |
| `id` | 土地 ID，用于标识唯一土地 | 使用 `ctx.uuid()` |
| `owner` | 土地所有者 | address |
| `seed` | 标记土地上所种植的作物 | 此处应为植物的 `id` |
| `property` | 土地具有的对种植有影响的属性 | 枚举类型，需要确定包含哪些属性 |
| `plant_timestamp` | 种子种植时间 | timestamp |

对于 `property` ，目前准备包含以下属性:

- `Normal` 普通属性，可以种植地球种子
- `Hot` 炎热属性，作用待定，名称可修改
- `Cold` 寒冷属性，作用待定，名称可修改

对于上述属性出现的几率待定

- 种子这个属性对应的数据是什么？

| 属性 | 作用 | 备注 |
| ---- | ----- | ----- |
| `name` | 种子的名字 | felt252 |
| `interval` | 种子种植时间 |  |

- 农场守护者这个属性对应的数据是什么？

| 属性 | 作用 | 备注 |
| ---- | ----- | ----- |
| `name` | 守护者的名字 | felt252 |
| `level` | 守护者的等级 |  |

- 化肥这个属性对应的数据是什么？

| 属性 | 作用 | 备注 |
| ---- | ----- | ----- |
| `name` | 化肥的名字  |  |

**Comment by yanboishere** [comment]
属性
